### ISSUE TITLE
Gem is missing

### ISSUE THREAD

**Issue by dayash** [simi/omniauth-office365#3]
When running gem install omniauth-office365 I get the following:
 Could not find a valid gem 'omniauth-office365' (>= 0) in any repository

Thanks for your help!

**Comment by simi** [comment]
This gem is not released yet. Can you try it first with this in Gemfile:

``` ruby
gem 'omniauth-office365', github: 'simi/omniauth-office365'
```

**Comment by dayash** [comment]
Oh, got it. Thanks for the quick response!

**Comment by simi** [comment]
fixed in https://github.com/simi/omniauth-office365/commit/b956ac59838da3393a0246ff711d8ceabd039bf0
