### ISSUE TITLE
CSRF detected

### ISSUE THREAD

**Issue by dayash** [simi/omniauth-office365#4]
I don't know if this is an issue or just me doing something wrong but I keep getting the following error:
(office365) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

I redirect the browser to https://login.windows.net/common/oauth2/authorize?response_type=code&client_id=[my client id]

The office authentication works fine and it redirects back to my callback page, and then I get that error. 

Is there anything you can advise?

**Comment by simi** [comment]
Can you ping me at retro@ballgag.cz? I have not access to office365 right now, so it will be nice if you are able to provide me some testing access (mainly id and secret) to some test app so i can dig deeper into this.

**Comment by simi** [comment]
@dayash is this solved?

**Comment by dayash** [comment]
Yes, thx.
